import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    formats: ['image/avif', 'image/webp'],
    minimumCacheTTL: 31536000,
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'specializedplasticsurgery.com',
      },
    ],
  },
  async redirects() {
    return [
      // Pages merged into /about
      { source: "/about-us", destination: "/about", permanent: true },
      { source: "/about-us/", destination: "/about", permanent: true },
      { source: "/our-philosophy", destination: "/about", permanent: true },
      { source: "/our-philosophy/", destination: "/about", permanent: true },
      { source: "/meet-our-expert-plastic-surgeons", destination: "/about", permanent: true },
      { source: "/meet-our-expert-plastic-surgeons/", destination: "/about", permanent: true },
      { source: "/image-credits", destination: "/about", permanent: true },
      { source: "/image-credits/", destination: "/about", permanent: true },

      // Doctor pages
      { source: "/michael-sosin-md-facs", destination: "/doctors/michael-sosin", permanent: true },
      { source: "/michael-sosin-md-facs/", destination: "/doctors/michael-sosin", permanent: true },
      { source: "/chris-devulapalli-md", destination: "/doctors/chris-devulapalli", permanent: true },
      { source: "/chris-devulapalli-md/", destination: "/doctors/chris-devulapalli", permanent: true },

      // Team, locations, contact
      { source: "/our-team", destination: "/team", permanent: true },
      { source: "/our-team/", destination: "/team", permanent: true },
      { source: "/our-locations", destination: "/locations", permanent: true },
      { source: "/our-locations/", destination: "/locations", permanent: true },
      { source: "/new-jersey", destination: "/locations#nj", permanent: true },
      { source: "/new-jersey/", destination: "/locations#nj", permanent: true },
      { source: "/new-york", destination: "/locations#ny", permanent: true },
      { source: "/new-york/", destination: "/locations#ny", permanent: true },
      { source: "/contact-us", destination: "/contact", permanent: true },
      { source: "/contact-us/", destination: "/contact", permanent: true },

      // Info pages

      // Breast reconstruction
      { source: "/breast-reconstruction", destination: "/services/breast-reconstruction", permanent: true },
      { source: "/breast-reconstruction/", destination: "/services/breast-reconstruction", permanent: true },
      { source: "/natural-tissue-flap-reconstruction", destination: "/services/breast-reconstruction/natural-tissue-flap", permanent: true },
      { source: "/natural-tissue-flap-reconstruction/", destination: "/services/breast-reconstruction/natural-tissue-flap", permanent: true },
      { source: "/implant-based-reconstruction", destination: "/services/breast-reconstruction/implant-based", permanent: true },
      { source: "/implant-based-reconstruction/", destination: "/services/breast-reconstruction/implant-based", permanent: true },
      { source: "/oncoplastic-breast-reduction", destination: "/services/breast-reconstruction/oncoplastic", permanent: true },
      { source: "/oncoplastic-breast-reduction/", destination: "/services/breast-reconstruction/oncoplastic", permanent: true },
      { source: "/preserving-nipple-sensation", destination: "/services/breast-reconstruction/resensation", permanent: true },
      { source: "/preserving-nipple-sensation/", destination: "/services/breast-reconstruction/resensation", permanent: true },
      { source: "/aesthetic-flat-closure", destination: "/services/breast-reconstruction/specialized", permanent: true },
      { source: "/aesthetic-flat-closure/", destination: "/services/breast-reconstruction/specialized", permanent: true },
      { source: "/nipple-areolar-reconstruction", destination: "/services/breast-reconstruction/specialized", permanent: true },
      { source: "/nipple-areolar-reconstruction/", destination: "/services/breast-reconstruction/specialized", permanent: true },
      { source: "/improving-prior-breast-reconstruction", destination: "/services/breast-reconstruction/revision", permanent: true },
      { source: "/improving-prior-breast-reconstruction/", destination: "/services/breast-reconstruction/revision", permanent: true },
      { source: "/male-breast-reconstruction", destination: "/services/breast-reconstruction/specialized", permanent: true },
      { source: "/male-breast-reconstruction/", destination: "/services/breast-reconstruction/specialized", permanent: true },
      { source: "/lymphedema-surgery", destination: "/services/breast-reconstruction/specialized", permanent: true },
      { source: "/lymphedema-surgery/", destination: "/services/breast-reconstruction/specialized", permanent: true },

      // Aesthetic breast
      { source: "/aesthetic-surgery", destination: "/services/aesthetic-breast", permanent: true },
      { source: "/aesthetic-surgery/", destination: "/services/aesthetic-breast", permanent: true },
      { source: "/breast-augmentation", destination: "/services/aesthetic-breast/augmentation", permanent: true },
      { source: "/breast-augmentation/", destination: "/services/aesthetic-breast/augmentation", permanent: true },
      { source: "/breast-implant-options", destination: "/services/aesthetic-breast/augmentation", permanent: true },
      { source: "/breast-implant-options/", destination: "/services/aesthetic-breast/augmentation", permanent: true },
      { source: "/breast-augmentation-revision", destination: "/services/aesthetic-breast/augmentation", permanent: true },
      { source: "/breast-augmentation-revision/", destination: "/services/aesthetic-breast/augmentation", permanent: true },
      { source: "/breast-augmentation-westchester", destination: "/services/aesthetic-breast/augmentation", permanent: true },
      { source: "/breast-augmentation-westchester/", destination: "/services/aesthetic-breast/augmentation", permanent: true },
      { source: "/fat-grafting-breast-augmentation", destination: "/services/aesthetic-breast/augmentation", permanent: true },
      { source: "/fat-grafting-breast-augmentation/", destination: "/services/aesthetic-breast/augmentation", permanent: true },
      { source: "/breast-lift", destination: "/services/aesthetic-breast/lift", permanent: true },
      { source: "/breast-lift/", destination: "/services/aesthetic-breast/lift", permanent: true },
      { source: "/breast-reduction", destination: "/services/aesthetic-breast/reduction", permanent: true },
      { source: "/breast-reduction/", destination: "/services/aesthetic-breast/reduction", permanent: true },
      { source: "/breast-reconstruction-coverage", destination: "/insurance", permanent: true },
      { source: "/breast-reconstruction-coverage/", destination: "/insurance", permanent: true },
      { source: "/breast-implant-removal", destination: "/services/aesthetic-breast/implant-removal", permanent: true },
      { source: "/breast-implant-removal/", destination: "/services/aesthetic-breast/implant-removal", permanent: true },

      // Face
      { source: "/face-lift", destination: "/services/face/facelift", permanent: true },
      { source: "/face-lift/", destination: "/services/face/facelift", permanent: true },
      { source: "/neck-lift", destination: "/services/face/neck-lift", permanent: true },
      { source: "/neck-lift/", destination: "/services/face/neck-lift", permanent: true },
      { source: "/rhinoplasty", destination: "/services/face/rhinoplasty", permanent: true },
      { source: "/rhinoplasty/", destination: "/services/face/rhinoplasty", permanent: true },
      { source: "/blepharoplasty", destination: "/services/face/blepharoplasty", permanent: true },
      { source: "/blepharoplasty/", destination: "/services/face/blepharoplasty", permanent: true },
      { source: "/otoplasty", destination: "/services/face/otoplasty", permanent: true },
      { source: "/otoplasty/", destination: "/services/face/otoplasty", permanent: true },
      { source: "/chin-liposuction", destination: "/services/face/chin-liposuction", permanent: true },
      { source: "/chin-liposuction/", destination: "/services/face/chin-liposuction", permanent: true },

      // Body
      { source: "/liposuction", destination: "/services/body/liposuction", permanent: true },
      { source: "/liposuction/", destination: "/services/body/liposuction", permanent: true },
      { source: "/liposuction-westchester", destination: "/services/body/liposuction", permanent: true },
      { source: "/liposuction-westchester/", destination: "/services/body/liposuction", permanent: true },
      { source: "/lipo-360", destination: "/services/body/lipo-360", permanent: true },
      { source: "/lipo-360/", destination: "/services/body/lipo-360", permanent: true },
      { source: "/brazilian-butt-lift", destination: "/services/body/bbl", permanent: true },
      { source: "/brazilian-butt-lift/", destination: "/services/body/bbl", permanent: true },
      { source: "/tummy-tuck", destination: "/services/body/tummy-tuck", permanent: true },
      { source: "/tummy-tuck/", destination: "/services/body/tummy-tuck", permanent: true },
      { source: "/mommy-makeover", destination: "/services/body/mommy-makeover", permanent: true },
      { source: "/mommy-makeover/", destination: "/services/body/mommy-makeover", permanent: true },
      { source: "/body-lift", destination: "/services/body/body-lift", permanent: true },
      { source: "/body-lift/", destination: "/services/body/body-lift", permanent: true },
      { source: "/thigh-lift", destination: "/services/body/thigh-lift", permanent: true },
      { source: "/thigh-lift/", destination: "/services/body/thigh-lift", permanent: true },
      { source: "/arm-lift", destination: "/services/body/arm-lift", permanent: true },
      { source: "/arm-lift/", destination: "/services/body/arm-lift", permanent: true },
      { source: "/gynecomastia", destination: "/services/aesthetic-breast/gynecomastia", permanent: true },
      { source: "/gynecomastia/", destination: "/services/aesthetic-breast/gynecomastia", permanent: true },

      // Gallery
      { source: "/gallery/breast-reconstruction/:path+", destination: "/gallery/breast-reconstruction", permanent: true },
      { source: "/gallery/aesthetic-breast-surgery/:path*", destination: "/gallery/aesthetic-breast", permanent: true },
      { source: "/gallery/breast-augmentation-fat-transfer", destination: "/gallery", permanent: true },
      { source: "/gallery/breast-augmentation-fat-transfer/", destination: "/gallery", permanent: true },
      { source: "/gallery/brest-lift-mastopexy", destination: "/gallery", permanent: true },
      { source: "/gallery/brest-lift-mastopexy/", destination: "/gallery", permanent: true },
      { source: "/gallery/abdominoplasty", destination: "/gallery", permanent: true },
      { source: "/gallery/abdominoplasty/", destination: "/gallery", permanent: true },

      // Blog posts
      { source: "/educational-resources", destination: "/blog", permanent: true },
      { source: "/educational-resources/", destination: "/blog", permanent: true },
      { source: "/silicone-vs-saline-breast-implants", destination: "/blog/silicone-vs-saline-breast-implants", permanent: true },
      { source: "/silicone-vs-saline-breast-implants/", destination: "/blog/silicone-vs-saline-breast-implants", permanent: true },
      { source: "/how-long-do-breast-implants-last", destination: "/blog/how-long-do-breast-implants-last", permanent: true },
      { source: "/how-long-do-breast-implants-last/", destination: "/blog/how-long-do-breast-implants-last", permanent: true },
      { source: "/do-i-need-a-breast-lift-with-implants", destination: "/blog/do-i-need-a-breast-lift-with-implants", permanent: true },
      { source: "/do-i-need-a-breast-lift-with-implants/", destination: "/blog/do-i-need-a-breast-lift-with-implants", permanent: true },
      { source: "/what-size-breast-implants-should-i-get", destination: "/blog/what-size-breast-implants-should-i-get", permanent: true },
      { source: "/what-size-breast-implants-should-i-get/", destination: "/blog/what-size-breast-implants-should-i-get", permanent: true },
      { source: "/round-vs-teardrop-breast-implants", destination: "/blog/round-vs-teardrop-breast-implants", permanent: true },
      { source: "/round-vs-teardrop-breast-implants/", destination: "/blog/round-vs-teardrop-breast-implants", permanent: true },
      { source: "/over-vs-under-muscle-breast-implants", destination: "/blog/over-vs-under-muscle-breast-implants", permanent: true },
      { source: "/over-vs-under-muscle-breast-implants/", destination: "/blog/over-vs-under-muscle-breast-implants", permanent: true },
      { source: "/breast-augmentation-westchester-ny", destination: "/blog/breast-augmentation-westchester-ny", permanent: true },
      { source: "/breast-augmentation-westchester-ny/", destination: "/blog/breast-augmentation-westchester-ny", permanent: true },
      { source: "/bbl-in-westchester-ny", destination: "/blog/bbl-in-westchester-ny", permanent: true },
      { source: "/bbl-in-westchester-ny/", destination: "/blog/bbl-in-westchester-ny", permanent: true },
      { source: "/lipo-360-in-westchester-ny", destination: "/blog/lipo-360-in-westchester-ny", permanent: true },
      { source: "/lipo-360-in-westchester-ny/", destination: "/blog/lipo-360-in-westchester-ny", permanent: true },
      { source: "/chin-liposuction-in-westchester-ny", destination: "/blog/chin-liposuction-in-westchester-ny", permanent: true },
      { source: "/chin-liposuction-in-westchester-ny/", destination: "/blog/chin-liposuction-in-westchester-ny", permanent: true },
      { source: "/unwrap-your-confidence-why-the-holiday-season-is-the-perfect-time-for-plastic-surgery-in-new-york", destination: "/blog/holiday-season-plastic-surgery", permanent: true },
      { source: "/unwrap-your-confidence-why-the-holiday-season-is-the-perfect-time-for-plastic-surgery-in-new-york/", destination: "/blog/holiday-season-plastic-surgery", permanent: true },
      { source: "/breast-cancer-awareness-month-recap-supporting-our-community-in-westchester-ny", destination: "/blog/breast-cancer-awareness-month-recap", permanent: true },
      { source: "/breast-cancer-awareness-month-recap-supporting-our-community-in-westchester-ny/", destination: "/blog/breast-cancer-awareness-month-recap", permanent: true },
      { source: "/refresh-your-look-with-blepharoplasty-in-westchester-ny", destination: "/blog/blepharoplasty-in-westchester-ny", permanent: true },
      { source: "/refresh-your-look-with-blepharoplasty-in-westchester-ny/", destination: "/blog/blepharoplasty-in-westchester-ny", permanent: true },
      { source: "/summer-confidence-boost", destination: "/blog/summer-confidence-boost", permanent: true },
      { source: "/summer-confidence-boost/", destination: "/blog/summer-confidence-boost", permanent: true },
      { source: "/breast-reduction-covered-by-insurance", destination: "/blog/breast-reduction-covered-by-insurance", permanent: true },
      { source: "/breast-reduction-covered-by-insurance/", destination: "/blog/breast-reduction-covered-by-insurance", permanent: true },
      { source: "/introducing-motiva-the-pinnacle-of-breast-implant-innovation", destination: "/blog/introducing-motiva-implants", permanent: true },
      { source: "/introducing-motiva-the-pinnacle-of-breast-implant-innovation/", destination: "/blog/introducing-motiva-implants", permanent: true },
      { source: "/summer-ready-why-now-is-the-best-time-for-a-tummy-tuck-liposuction-or-breast-augmentation", destination: "/blog/summer-ready-plastic-surgery", permanent: true },
      { source: "/summer-ready-why-now-is-the-best-time-for-a-tummy-tuck-liposuction-or-breast-augmentation/", destination: "/blog/summer-ready-plastic-surgery", permanent: true },
      { source: "/meet-the-experts", destination: "/blog/meet-the-experts", permanent: true },
      { source: "/meet-the-experts/", destination: "/blog/meet-the-experts", permanent: true },
      { source: "/restoring-what-matters", destination: "/blog/restoring-what-matters", permanent: true },
      { source: "/restoring-what-matters/", destination: "/blog/restoring-what-matters", permanent: true },
      { source: "/a-mommy-makeover", destination: "/blog/a-mommy-makeover", permanent: true },
      { source: "/a-mommy-makeover/", destination: "/blog/a-mommy-makeover", permanent: true },
      { source: "/celebrating-breast-cancer-awareness-month", destination: "/blog/celebrating-breast-cancer-awareness-month", permanent: true },
      { source: "/celebrating-breast-cancer-awareness-month/", destination: "/blog/celebrating-breast-cancer-awareness-month", permanent: true },
      { source: "/wrapping-up-breast-cancer-awareness-month", destination: "/blog/wrapping-up-breast-cancer-awareness-month", permanent: true },
      { source: "/wrapping-up-breast-cancer-awareness-month/", destination: "/blog/wrapping-up-breast-cancer-awareness-month", permanent: true },
      { source: "/breast-augmentation-with-lift-mastopexy-in-harrison-ny-what-you-need-to-know", destination: "/blog/breast-augmentation-with-lift-harrison-ny", permanent: true },
      { source: "/breast-augmentation-with-lift-mastopexy-in-harrison-ny-what-you-need-to-know/", destination: "/blog/breast-augmentation-with-lift-harrison-ny", permanent: true },
      { source: "/breast-augmentation-with-lift-in-westchester-county-ny-the-dual-plane-technique-explained", destination: "/blog/dual-plane-technique-explained", permanent: true },
      { source: "/breast-augmentation-with-lift-in-westchester-county-ny-the-dual-plane-technique-explained/", destination: "/blog/dual-plane-technique-explained", permanent: true },
      { source: "/high-profile-breast-implants-with-the-dual-plane-technique-in-westchester-ny", destination: "/blog/high-profile-implants-dual-plane", permanent: true },
      { source: "/high-profile-breast-implants-with-the-dual-plane-technique-in-westchester-ny/", destination: "/blog/high-profile-implants-dual-plane", permanent: true },
      { source: "/breast-implant-removal-lift-fat-grafting-westchester-ny", destination: "/blog/breast-implant-removal-lift-fat-grafting", permanent: true },
      { source: "/breast-implant-removal-lift-fat-grafting-westchester-ny/", destination: "/blog/breast-implant-removal-lift-fat-grafting", permanent: true },
    ];
  },
};

export default nextConfig;
